src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>winet_id__c</fullName>
        <label>winet id</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/caesars_gst_id_xref__x.object
<CustomObject>
    <description>caesars$gst_id_xref</description>
    <externalDataSource>CustomApexHerokuConnector</externalDataSource>
    <externalName>caesars$gst_id_xref</externalName>
    <fields>
        <fullName>i_dmid__c</fullName>
        <description>i_dmid</description>
        <externalDeveloperName>i_dmid</externalDeveloperName>
        <label>i_dmid</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>i_xref_dmid__c</fullName>
        <description>i_xref_dmid</description>
        <externalDeveloperName>i_xref_dmid</externalDeveloperName>
        <label>i_xref_dmid</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <label>caesars$gst_id_xref</label>
    <pluralLabel>caesars$gst_id_xref</pluralLabel>
</CustomObject>

src/objects/CaesarsSetup__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>turnOffContactTrigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>turnOffContactTrigger</label>
        <type>Checkbox</type>
    </fields>
    <label>CaesarsSetup</label>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>winet_Id__c</fullName>
        <externalId>true</externalId>
        <label>winet Id</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/guest_hotel_activity_vedw__x.object
<CustomObject>
    <description>guest_hotel_activity_vedw</description>
    <externalDataSource>CustomApexHerokuConnector</externalDataSource>
    <externalName>caesars$gst_hotel_activity_vedw</externalName>
    <fields>
        <fullName>contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <externalDeveloperName>contact_fk</externalDeveloperName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Guest Hotel Activity Vedvs</relationshipLabel>
        <relationshipName>guest_hotel_activity_vedw</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>i_dmid__c</fullName>
        <description>i_dmid</description>
        <externalDeveloperName>i_dmid</externalDeveloperName>
        <label>i_dmid</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <label>Guest Hotel Activity Vedv</label>
    <pluralLabel>Guest Hotel Activity Vedvs</pluralLabel>
</CustomObject>

src/objects/lms_folio_dtl__x.object
<CustomObject>
    <description>caesars$lms_folio_dtl</description>
    <externalDataSource>CustomApexHerokuConnector</externalDataSource>
    <externalName>caesars$lms_folio_dtl</externalName>
    <fields>
        <fullName>lms_folio_hdr_fk__c</fullName>
        <externalDeveloperName>lms_folio_hdr_fk</externalDeveloperName>
        <label>LMS Folio Hdr</label>
        <length>18</length>
        <referenceTo>lms_folio_hdr__x</referenceTo>
        <relationshipLabel>LMS Folio Dtl</relationshipLabel>
        <relationshipName>LMS_Folio_Dtl</relationshipName>
        <type>ExternalLookup</type>
    </fields>
    <label>LMS Folio Dtl</label>
    <pluralLabel>LMS Folio Dtl</pluralLabel>
</CustomObject>

src/objects/lms_folio_hdr__x.object
<CustomObject>
    <description>lms_folio_hdr</description>
    <externalDataSource>CustomApexHerokuConnector</externalDataSource>
    <externalName>caesars$lms_folio_hdr</externalName>
    <fields>
        <fullName>lms_hotel_activity_fk__c</fullName>
        <externalDeveloperName>lms_hotel_activity_fk</externalDeveloperName>
        <label>LMS Hotel Activity</label>
        <length>18</length>
        <referenceTo>lms_hotel_activity__x</referenceTo>
        <relationshipLabel>lms_folio_hdr</relationshipLabel>
        <relationshipName>lms_folio_hdr</relationshipName>
        <type>ExternalLookup</type>
    </fields>
    <label>LMS Folio Hdr</label>
    <pluralLabel>LMS Folio Hdr</pluralLabel>
</CustomObject>

src/objects/lms_hotel_activity__x.object
<CustomObject>
    <description>lms_hotel_activity</description>
    <externalDataSource>CustomApexHerokuConnector</externalDataSource>
    <externalName>caesars$lms_hotel_activity</externalName>
    <fields>
        <fullName>contact1__c</fullName>
        <externalDeveloperName>contact_pri_fk</externalDeveloperName>
        <label>Contact</label>
        <length>18</length>
        <referenceTargetField>Contact.ContactId__c</referenceTargetField>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Primary LMS Hotel Activities</relationshipLabel>
        <relationshipName>lms_hotel_activity</relationshipName>
        <type>IndirectLookup</type>
    </fields>
    <fields>
        <fullName>i_xref_dmid__c</fullName>
        <description>i_xref_dmid</description>
        <externalDeveloperName>i_xref_dmid</externalDeveloperName>
        <label>i_xref_dmid</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <label>LMS Hotel Activity</label>
    <pluralLabel>LMS Hotel Activities</pluralLabel>
</CustomObject>

src/classes/GuestHotelFolioTest.cls
@isTest
private class GuestHotelFolioTest {
	
	@testSetup  static void testSetup() {
		CaesarsSetup__c csetup = new CaesarsSetup__c(
			Name = 'Contact',
			turnOffContactTrigger__c = false
			);
		insert csetup;

		Account acct = AccountBuilder.buildAccount()
		.withName('Account1')
		.withWinetId('111')
		.get();

		insert acct;
		
		Contact c = ContactBuilder.buildContact()
		.withFirstName('MyFirstName')
		.withLastName('MyLastName')
		.withWinetId('111')
		.withAccount(acct.id).get();
		
		insert c;

		Contact cXref = ContactBuilder.buildContact()
		.withFirstName('MyFirstNameX')
		.withLastName('MyLastNameX')
		.withWinetId('333')
		.withAccount(acct.id).get();

		insert cXref;
	}

	@isTest static void testActivityMock() {
		String cId = [SELECT Id FROM Contact LIMIT 1].id;
		Test.startTest();
	    lms_hotel_activity__x mockedRequest = new lms_hotel_activity__x(
	        contact1__c = cId
	    );

	    List<Id> contactIds = new List<Id>();
	    contactIds.add(cId);

	    GuestHotelFolioDataCC.mockedActivity.add(mockedRequest);
	    List<GuestHotelFolioDataCC.ActivityWrapper> requestList = 
	    		GuestHotelFolioDataCC.retrieveHotelActivityByContacts(contactIds);
	    Test.stopTest();

	    system.debug('*** requestList ' + requestList);

	    System.assertEquals(1, requestList.size(), 'There should be 1 Activity record'); 
	    System.assertEquals(cId, requestList[0].contact1, 'The Activity record should be for the contact'); 
	
	}

	@isTest static void testActivityVEDWMock() {
		String cId = [SELECT Id FROM Contact LIMIT 1].id;
		Test.startTest();
	    guest_hotel_activity_vedw__x mockedVEDWRequest = new guest_hotel_activity_vedw__x(
	        contact__c = cId
	    );

	    List<Id> contactIds = new List<Id>();
	    contactIds.add(cId);

	    GuestHotelFolioDataCC.mockedActivityVEDW.add(mockedVEDWRequest);
	    List<GuestHotelFolioDataCC.ActivityVEDWWrapper> requestList = 
	    		GuestHotelFolioDataCC.retrieveHotelActivityVEDWByContacts(contactIds);
	    Test.stopTest();

	    system.debug('*** requestList ' + requestList);

	    System.assertEquals(1, requestList.size(), 'There should be 1 Activity VEDW record'); 
	    System.assertEquals(cId, requestList[0].contact, 'The Activity VEDW record should be for the contact'); 
	
	}

	@isTest static void testFolioHeaderMock() {
		String cId = [SELECT Id FROM Contact LIMIT 1].id;
		lms_hotel_activity__x mockedRequest = new lms_hotel_activity__x(
			contact1__c = cId,
	        ExternalId = '111' 
	    );

	    List<Id> contactIds = new List<Id>();
	    contactIds.add(cId);

	    GuestHotelFolioDataCC.mockedActivity.add(mockedRequest);
	    List<GuestHotelFolioDataCC.ActivityWrapper> requestList = 
	    		GuestHotelFolioDataCC.retrieveHotelActivityByContacts(contactIds);

		Test.startTest();
	    lms_folio_hdr__x mockedHdrRequest = new lms_folio_hdr__x(
	        lms_hotel_activity_fk__c = '111'
	    );

	    GuestHotelFolioDataCC.mockedFolioHeader.add(mockedHdrRequest);
	    List<GuestHotelFolioDataCC.FolioHeaderWrapper> requestListHdr = 
	    		GuestHotelFolioDataCC.retrieveFolioHeaderByContacts(contactIds);
	    Test.stopTest();

	    system.debug('*** requestListHdr ' + requestListHdr);

	    System.assertEquals(1, requestListHdr.size(), 'There should be 1 Folio Header record'); 
	    System.assertEquals('111', requestListHdr[0].lms_hotel_activity_fk, 'The Folio Header record should be for the Hotel Activity'); 
	}

	@isTest static void testFolioDetailsMock() {
		String cId = [SELECT Id FROM Contact LIMIT 1].id;
		lms_hotel_activity__x mockedRequest = new lms_hotel_activity__x(
			contact1__c = cId,
	        ExternalId = '111' 
	    );

	    List<Id> contactIds = new List<Id>();
	    contactIds.add(cId);

	    GuestHotelFolioDataCC.mockedActivity.add(mockedRequest);
	    List<GuestHotelFolioDataCC.ActivityWrapper> requestList = 
	    		GuestHotelFolioDataCC.retrieveHotelActivityByContacts(contactIds);

	      lms_folio_hdr__x mockedHdrRequest = new lms_folio_hdr__x(
	        lms_hotel_activity_fk__c = '111',
	        ExternalId = '222'
	    );

	    GuestHotelFolioDataCC.mockedFolioHeader.add(mockedHdrRequest);
	    List<GuestHotelFolioDataCC.FolioHeaderWrapper> requestListHdr = 
	    		GuestHotelFolioDataCC.retrieveFolioHeaderByContacts(contactIds);		

		Test.startTest();
	    lms_folio_dtl__x mockedDtlRequest = new lms_folio_dtl__x(
	        lms_folio_hdr_fk__c = '222'
	    );

	    GuestHotelFolioDataCC.mockedFolioDetails.add(mockedDtlRequest);
	    List<GuestHotelFolioDataCC.FolioDetailsWrapper> requestListDtl = 
	    		GuestHotelFolioDataCC.retrieveFolioDetailsByContacts(contactIds);
	    Test.stopTest();

	    system.debug('*** requestListDtl ' + requestListDtl);

	    System.assertEquals(1, requestListDtl.size(), 'There should be 1 Folio Details record'); 
	    System.assertEquals('222', requestListDtl[0].lms_folio_hdr_fk, 'The Folio Details record should be for the Folio Header'); 
	}

	@isTest static void testXref() {
		List<Id> contactIds = new List<Id>();	    
		for (Contact c : [SELECT Id FROM Contact WHERE FirstName in ('MyFirstName', 'MyFirstNameX') LIMIT 2]){
			contactIds.add(c.Id);
		}

		String winetId = [SELECT winet_Id__c FROM Contact WHERE FirstName in ('MyFirstName') LIMIT 1].winet_Id__c;
		Test.startTest();
	    caesars_gst_id_xref__x mockedXrefX = new caesars_gst_id_xref__x(
	        i_xref_dmid__c = '333',
	        i_dmid__c = '111'
	    );   

	    GuestHotelFolioDataCC.mockedXref.add(mockedXrefX);
	    List<String> requestListX = 
	    		GuestHotelFolioDataCC.getXrefIds(contactIds);
	    Test.stopTest();

	    system.debug('*** requestListX ' + requestListX);

	    System.assertEquals(3, requestListX.size(), 'There should be 3 contacts'); 
	
	}

	@isTest static void testActivityMockDetails() {
		String cId = [SELECT Id FROM Contact LIMIT 1].id;
		Test.startTest();
	    lms_hotel_activity__x mockedRequest = new lms_hotel_activity__x(
	        contact1__c = cId,
	        ExternalId = '111'
	    );

	  	List<String> externalIds = new List<String>();
	    externalIds.add('111');

	    GuestHotelFolioDataCC.mockedActivity.add(mockedRequest);
	    List<GuestHotelFolioDataCC.ActivityWrapper> requestList = 
	    		GuestHotelFolioDataCC.retrieveHotelActivityDetails(externalIds);
	    Test.stopTest();

	    system.debug('*** requestList ' + requestList);

	    System.assertEquals(1, requestList.size(), 'There should be 1 Activity record'); 
	    System.assertEquals(cId, requestList[0].contact1, 'The Activity record should be for the contact'); 
	
	}

	@isTest static void testActivityVEDWMockDetails() {
		String cId = [SELECT Id FROM Contact LIMIT 1].id;
		Test.startTest();
	    guest_hotel_activity_vedw__x mockedVEDWRequest = new guest_hotel_activity_vedw__x(
	        contact__c = cId,
	        ExternalId = '111'
	    );

	    List<String> externalIds = new List<String>();
	    externalIds.add('111');

	    GuestHotelFolioDataCC.mockedActivityVEDW.add(mockedVEDWRequest);
	    List<GuestHotelFolioDataCC.ActivityVEDWWrapper> requestList = 
	    		GuestHotelFolioDataCC.retrieveHotelActivityVEDWDetails(externalIds);
	    Test.stopTest();

	    system.debug('*** requestList ' + requestList);

	    System.assertEquals(1, requestList.size(), 'There should be 1 Activity VEDW record'); 
	    System.assertEquals(cId, requestList[0].contact, 'The Activity VEDW record should be for the contact'); 
	
	}

	@isTest static void testFolioHeaderMockDetails() {
		String cId = [SELECT Id FROM Contact LIMIT 1].id;
		lms_hotel_activity__x mockedRequest = new lms_hotel_activity__x(
			contact1__c = cId,
	        ExternalId = '111' 
	    );

	    List<String> externalIds = new List<String>();
	    externalIds.add('111');

		Test.startTest();
	    lms_folio_hdr__x mockedHdrRequest = new lms_folio_hdr__x(
	        lms_hotel_activity_fk__c = '222'
	    );

	    GuestHotelFolioDataCC.mockedFolioHeader.add(mockedHdrRequest);
	    List<GuestHotelFolioDataCC.FolioHeaderWrapper> requestListHdr = 
	    		GuestHotelFolioDataCC.retrieveFolioHeaderDetails(externalIds);
	    Test.stopTest();

	    system.debug('*** requestListHdr ' + requestListHdr);

	    System.assertEquals(1, requestListHdr.size(), 'There should be 1 Folio Header record'); 
	    System.assertEquals('222', requestListHdr[0].lms_hotel_activity_fk, 'The Folio Header record should be for the Hotel Activity'); 
	}

	@isTest static void testFolioDetailsMockDetails() {
		String cId = [SELECT Id FROM Contact LIMIT 1].id;
		lms_hotel_activity__x mockedRequest = new lms_hotel_activity__x(
			contact1__c = cId,
	        ExternalId = '111' 
	    );	

	    List<String> externalIds = new List<String>();
	    externalIds.add('111');

		Test.startTest();
	    lms_folio_dtl__x mockedDtlRequest = new lms_folio_dtl__x(
	        lms_folio_hdr_fk__c = '222'
	    );

	    GuestHotelFolioDataCC.mockedFolioDetails.add(mockedDtlRequest);
	    List<GuestHotelFolioDataCC.FolioDetailsWrapper> requestListDtl = 
	    		GuestHotelFolioDataCC.retrieveFolioDetailsDetails(externalIds);
	    Test.stopTest();

	    system.debug('*** requestListDtl ' + requestListDtl);

	    System.assertEquals(1, requestListDtl.size(), 'There should be 1 Folio Details record'); 
	    System.assertEquals('222', requestListDtl[0].lms_folio_hdr_fk, 'The Folio Details record should be for the Folio Header'); 
	}
}