src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Property</fullName>
        <active>true</active>
        <description>Property</description>
        <label>Property</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Campaign_Project__c.object
<CustomObject>
    <label>Campaign Project</label>
    <nameField>
        <displayFormat>CP{00000000}</displayFormat>
        <label>Campaign Project Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Projects</pluralLabel>
    <recordTypes>
        <fullName>Draft</fullName>
        <active>true</active>
        <description>Campaign Project in Draft Status</description>
        <label>Draft</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Offer_Definition__c.object
<CustomObject>
    <fields>
        <fullName>Campaign_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Campaign Project</description>
        <inlineHelpText>Campaign Project</inlineHelpText>
        <label>Campaign Project</label>
        <referenceTo>Campaign_Project__c</referenceTo>
        <relationshipLabel>Offer Definitions</relationshipLabel>
        <relationshipName>Offer_Definitions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Offer Definition</label>
    <nameField>
        <displayFormat>OD-{000000000}</displayFormat>
        <label>Offer Definition Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offer Definitions</pluralLabel>
    <recordTypes>
        <fullName>Choice</fullName>
        <active>true</active>
        <description>Choice Offer is also known as &apos;OR&apos; Offer. For example, Three free room night  OR  $50 casino play</description>
        <label>Choice</label>
    </recordTypes>
    <recordTypes>
        <fullName>Package</fullName>
        <active>true</active>
        <description>Package offer has multiple offer incentives. For example Three free room night  AND $50 casino play AND $50 F&amp;B credit</description>
        <label>Package</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RecordTypeModel.cls
/**
*	@description   model class for RecordType
*
*
*    @author Benjamin Lau
*    @date 01/14/2016
*    @group Model
*/
public  without Sharing class RecordTypeModel {

    /////////////////////////////////////////////////////////////////////////
    private static List<RecordType> pRecordTypeList = null;
    public static List<RecordType> recordTypeList {
        get {
            if (pRecordTypeList == null) {
                pRecordTypeList = [select id, SobjectType, DeveloperName, Name  from RecordType where isActive = true];
            }
            return pRecordTypeList;
        }
    }

    private static Map<Id, RecordType> pRecordTypeMapById = null;
    public static Map<Id, RecordType> recordTypeMapById {
        get {
            if ( pRecordTypeMapById == null) {
                pRecordTypeMapById = new Map<Id, RecordType>();
                for(RecordType rt : RecordTypeList) {
                    pRecordTypeMapById.put(rt.id, rt);
                }
            }
            return pRecordTypeMapById;
        }
    }

    public static string findRecordTypeNameById(Id recordTypeId) {
        if (RecordTypeMapById.containsKey(recordTypeId) ) {
            return RecordTypeMapById.get(recordTypeId).DeveloperName;
        } else {
            return 'Unknown RecordTypeId : ' + recordTypeId;
        }
    }

    private static Map<String,RecordType> pRecordTypeMap = null;
    public static Map<String,RecordType> recordTypeMap {
        get {
            if ( pRecordTypeMap == null){
                pRecordTypeMap = new Map<String,RecordType>();

                for(RecordType rt : RecordTypeList){
                    pRecordTypeMap.put(rt.SobjectType+':'+rt.Name, rt);
                    //System.Debug(rt.SobjectType+':'+rt.Name);
                    if ( rt.Name <> rt.DeveloperName){
                        pRecordTypeMap.put(rt.SobjectType+':'+rt.DeveloperName, rt);
                        //System.Debug(rt.SobjectType+':'+rt.DeveloperName);
                    }
                }
            }
            return pRecordTypeMap;
        }
    }

    public static RecordType lookupRecordType(string sObjectName, string RecordTypeName){
        if(recordTypeMap.containsKey(sObjectName+':'+RecordTypeName)){
            return recordTypeMap.get(sObjectName+':'+RecordTypeName);
        } else {
            //unable to locate
            System.Debug('RecordTypeModel::LookupRecordType unable to locate '+sObjectName+':'+RecordTypeName);
            return null;
        }
    }


    public static Id lookupRecordTypeId(string sObjectName, string recordTypeName){
        if(recordTypeMap.containsKey(sObjectName+':'+recordTypeName)){
            return recordTypeMap.get(sObjectName+':'+recordTypeName).Id;
        } else {
            //unable to locate
            System.Debug('RecordTypeModel::LookupRecordType unable to locate '+sObjectName+':'+recordTypeName);
            return null;
        }
    }


    ///////////////////////////////////////////////////////////////////////////////////////
    // Account
    public static id Account_PropertyId {
        get {
            return LookupRecordTypeId('Account','Property');
        }
    }

    ///////////////////////////////////////////////////////////////////////////////////////
    // Campaign Project
    public static id CampaignProject_DraftId {
        get {
            return LookupRecordTypeId('Campaign_Project__c','Draft');
        }
    }

    ///////////////////////////////////////////////////////////////////////////////////////
    // Offer Definition
    public static id OfferDefinition_ChoiceId {
        get {
            return LookupRecordTypeId('Offer_Definition__c','Choice');
        }
    }
    
    public static id OfferDefinition_PackageId {
        get {
            return LookupRecordTypeId('Offer_Definition__c','Package');
        }
    }



}