src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>POD__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Pod</description>
        <label>POD</label>
        <referenceTo>POD__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>winet_id__c</fullName>
        <label>winet id</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Property</fullName>
        <active>true</active>
        <description>Property</description>
        <label>Property</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Account_Type_Code__c.object
<CustomObject>
    <description>Account type dictionary</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quality_code__c</fullName>
        <label>Quality code</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_category__c</fullName>
        <label>Type category</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>Account Type Code</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Type Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CaesarsSetup__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>turnOffContactTrigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>turnOffContactTrigger</label>
        <type>Checkbox</type>
    </fields>
    <label>CaesarsSetup</label>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>winet_Id__c</fullName>
        <externalId>true</externalId>
        <label>winet Id</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/enterprise_campaign__x.object
<CustomObject>
    <description>enterprise_campaign</description>
    <externalDataSource>CustomApexHerokuConnector</externalDataSource>
    <externalName>caesars$marketing_campaigns_enterprise</externalName>
    <fields>
        <fullName>contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>contact</description>
        <externalDeveloperName>contact</externalDeveloperName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Marketing Enterprise Campaigns</relationshipLabel>
        <relationshipName>Enterprise_Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Marketing Enterprise Campaign</label>
    <pluralLabel>Marketing Enterprise Campaigns</pluralLabel>
</CustomObject>

src/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Active_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Active Flag</description>
        <inlineHelpText>Active Flag</inlineHelpText>
        <label>Active Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_Code__c</fullName>
        <description>Market Code</description>
        <globalPicklist>Market</globalPicklist>
        <label>Market Code</label>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>POD__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>POD associated with this market</description>
        <inlineHelpText>POD associated with this market</inlineHelpText>
        <label>POD</label>
        <referenceTo>POD__c</referenceTo>
        <relationshipLabel>Market</relationshipLabel>
        <relationshipName>Market</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Time_Zone__c</fullName>
        <globalPicklist>Time_Zone</globalPicklist>
        <label>Time Zone</label>
        <type>Picklist</type>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Market</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/marketing_campaigns__x.object
<CustomObject>
    <description>marketing_campaigns</description>
    <externalDataSource>CustomApexHerokuConnector</externalDataSource>
    <externalName>caesars$marketing_campaigns</externalName>
    <fields>
        <fullName>c_acct_type_cd_fk__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>c_acct_type_cd_fk</description>
        <externalDeveloperName>c_acct_type_cd_fk</externalDeveloperName>
        <label>Account Type</label>
        <referenceTo>Account_Type_Code__c</referenceTo>
        <relationshipName>public_marketing_campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>c_dom_cd_prop_fk__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>c_dom_cd_prop_fk</description>
        <externalDeveloperName>c_dom_cd_prop_fk</externalDeveloperName>
        <label>Dominant Code Property</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>public_marketing_campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>c_dom_market_cd_fk__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>c_dom_market_cd_fk</description>
        <externalDeveloperName>c_dom_market_cd_fk</externalDeveloperName>
        <label>Dominant Market Code</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipName>public_marketing_campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>c_prop_market_cd_fk__c</fullName>
        <description>c_prop_market_cd_fk</description>
        <externalDeveloperName>c_prop_market_cd_fk</externalDeveloperName>
        <label>c_prop_market_cd_fk</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>contact</description>
        <externalDeveloperName>contact</externalDeveloperName>
        <label>contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>public_marketing_campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>marketing_campaigns</label>
    <pluralLabel>marketing_campaigns</pluralLabel>
</CustomObject>

src/objects/marketing_campaigns_properties__x.object
<CustomObject>
    <description>marketing_campaigns_properties</description>
    <externalDataSource>CustomApexHerokuConnector</externalDataSource>
    <externalName>caesars$marketing_campaigns_properties</externalName>
    <fields>
        <fullName>c_acct_type_cd_fk__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>c_acct_type_cd_fk</description>
        <externalDeveloperName>c_acct_type_cd_fk</externalDeveloperName>
        <label>c_acct_type_cd_fk</label>
        <referenceTo>Account_Type_Code__c</referenceTo>
        <relationshipName>public_marketing_campaigns_properties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>c_dom_cd_prop_fk__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>c_dom_cd_prop_fk</description>
        <externalDeveloperName>c_dom_cd_prop_fk</externalDeveloperName>
        <label>c_dom_cd_prop_fk</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>public_marketing_campaigns_properties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>c_dom_market_cd_fk__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>c_dom_market_cd_fk</description>
        <externalDeveloperName>c_dom_market_cd_fk</externalDeveloperName>
        <label>c_dom_market_cd_fk</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipName>public_marketing_campaigns_properties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>c_prop_market_cd_fk__c</fullName>
        <description>c_prop_market_cd_fk</description>
        <externalDeveloperName>c_prop_market_cd_fk</externalDeveloperName>
        <label>c_prop_market_cd_fk</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>contact</description>
        <externalDeveloperName>contact</externalDeveloperName>
        <label>contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Marketing Campaigns Properties</relationshipLabel>
        <relationshipName>public_marketing_campaigns_properties</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Marketing Campaign Properties</label>
    <pluralLabel>Marketing Campaign Properties</pluralLabel>
</CustomObject>

src/objects/marketing_campaigns_weekly__x.object
<CustomObject>
    <description>marketing_campaigns_weekly</description>
    <externalDataSource>CustomApexHerokuConnector</externalDataSource>
    <externalName>caesars$marketing_campaigns_weekly</externalName>
    <fields>
        <fullName>c_acct_type_cd_fk__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>c_acct_type_cd_fk</label>
        <referenceTo>Account_Type_Code__c</referenceTo>
        <relationshipLabel>marketing_campaigns_weekly</relationshipLabel>
        <relationshipName>marketing_campaigns_weekly</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>c_prop_market_cd_fk__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>c_prop_market_cd_fk</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>marketing_campaigns_weekly</relationshipLabel>
        <relationshipName>marketing_campaigns_weekly</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Marketing Campaigns Weekly</relationshipLabel>
        <relationshipName>marketing_campaigns_weekly</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Marketing Campaign Weekly</label>
    <pluralLabel>Marketing Campaigns Weekly</pluralLabel>
</CustomObject>

src/objects/marketing_lvm__x.object
<CustomObject>
    <description>marketing_lvm</description>
    <externalDataSource>CustomApexHerokuConnector</externalDataSource>
    <externalName>caesars$marketing_campaigns_lvm</externalName>
    <fields>
        <fullName>c_acct_type_cd_fk__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account type code</label>
        <referenceTo>Account_Type_Code__c</referenceTo>
        <relationshipLabel>Marketing LVMs</relationshipLabel>
        <relationshipName>marketing_lvm</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>c_dom_cd_prop_fk__c</fullName>
        <description>c_dom_cd_prop_fk</description>
        <externalDeveloperName>c_dom_cd_prop_fk</externalDeveloperName>
        <label>c_dom_cd_prop_fk</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>c_prop_market_cd_fk__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Market code</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Marketing LVMs</relationshipLabel>
        <relationshipName>marketing_lvm</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>marketing_lvm</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Marketing LVM</label>
    <pluralLabel>Marketing LVMs</pluralLabel>
</CustomObject>

src/objects/POD__c.object
<CustomObject>
    <description>POD (Marketing)</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>POD Description</description>
        <inlineHelpText>POD Description</inlineHelpText>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>POD_Name__c</fullName>
        <description>POD Name</description>
        <globalPicklist>POD</globalPicklist>
        <inlineHelpText>POD Name</inlineHelpText>
        <label>POD Name</label>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>POD</label>
    <nameField>
        <displayFormat>P{00000}</displayFormat>
        <label>POD Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>POD</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GuestShelfDataTest.cls
@isTest
private class GuestShelfDataTest {
	
	@testSetup  static void testSetup() {
		CaesarsSetup__c csetup = new CaesarsSetup__c(
			Name = 'Contact',
			turnOffContactTrigger__c = false
			);
		insert csetup;

		Account acct = new Account(
			Name = 'Account1',
			winet_id__c = '111');
		insert acct;

		Account_Type_Code__c atc = new Account_Type_Code__c(
			Name = 'atcName',
			Description__c = 'atcDesc',			
			Quality_code__c = 'A',
			Type_category__c = 'BCD'
			);
		insert atc;

		Account propAcct = new Account(
			Name = 'DomPropAcctName'
			);
		insert propAcct;

		Pod__c pod = new Pod__c(
			POD_Name__c = 'Heartland POD'
			);
		insert pod;

		Market__c mkt = new Market__c(
			Name = 'mktName',
	  		Active_Flag__c = true,
	  		Description__c = 'mktDesc',
	  		Time_Zone__c = 'PST',
	  		Market_Code__c = 'ACM',
	  		POD__c = pod.Id);
		insert mkt;

		Contact c = new Contact (
			FirstName = 'MyFirstName',
			LastName = 'MyLastName',
			AccountId = acct.id
			);
		insert c;
	}

	@isTest static void testGetGuestShelfCampaignsMock() {
		String cId = [SELECT Id FROM Contact LIMIT 1].id;
		String atcId = [SELECT Id FROM Account_Type_Code__c LIMIT 1].id;
		String acctPropId = [SELECT Id FROM Account WHERE Name = 'DomPropAcctName' LIMIT 1].id;
		String mktId = [SELECT Id FROM Market__c LIMIT 1].id;
		Test.startTest();
	    marketing_campaigns__x mockedRequest = new marketing_campaigns__x(
	        contact__c = cId,
	        c_acct_type_cd_fk__c = atcId,
	        c_dom_cd_prop_fk__c = acctPropId,
	        c_dom_market_cd_fk__c = mktId
	    );

	    List<Id> contactIds = new List<Id>();
	    contactIds.add(cId);

	    GuestShelfDataCC.mockedRequests.add(mockedRequest);
	    List<GuestShelfDataCC.MarketingCampaignWrapper> requestList = 
	    		GuestShelfDataCC.retrieveMarketingCampaignByContacts(contactIds);
	    Test.stopTest();

	    system.debug('*** requestList ' + requestList);

	    System.assertEquals(1, requestList.size(), 'There should be 1 Marketing Campaign record'); 
	    System.assertEquals(cId, requestList[0].contact, 'The Marketing Campaign record should be for the contact'); 
	
	}

	@isTest static void testGetGuestShelfCampaignsPropMock() {
		String cId = [SELECT Id FROM Contact LIMIT 1].id;
		String atcId = [SELECT Id FROM Account_Type_Code__c LIMIT 1].id;
		String acctPropId = [SELECT Id FROM Account WHERE Name = 'DomPropAcctName' LIMIT 1].id;
		String mktId = [SELECT Id FROM Market__c LIMIT 1].id;
		Test.startTest();
	    marketing_campaigns_properties__x mockedPropRequest = new marketing_campaigns_properties__x(
	        contact__c = cId,
	        c_acct_type_cd_fk__c = atcId,
	        c_dom_cd_prop_fk__c = acctPropId,
	        c_dom_market_cd_fk__c = mktId
	    );

	    List<Id> contactIds = new List<Id>();
	    contactIds.add(cId);

	   GuestShelfDataCC.mockedPropRequests.add(mockedPropRequest);
	    List<GuestShelfDataCC.MarketingCampaignPropertyWrapper> requestList = 
	    		GuestShelfDataCC.retrieveMarketingCampaignPropByContacts(contactIds);
	    Test.stopTest();

	    system.debug('*** requestList ' + requestList);


	    System.assertEquals(1, requestList.size(), 'There should be 1 Marketing Campaign Property record'); 
	    System.assertEquals(cId, requestList[0].contact, 'The Marketing Campaign Property record should be for the contact'); 
	
	}

	@isTest static void testGetGuestShelfCampaignsWeeklyMock() {
		String cId = [SELECT Id FROM Contact LIMIT 1].id;
		String atcId = [SELECT Id FROM Account_Type_Code__c LIMIT 1].id;
		String mktId = [SELECT Id FROM Market__c LIMIT 1].id;
		Test.startTest();
	    marketing_campaigns_weekly__x mockedWeeklyRequest = new marketing_campaigns_weekly__x(
	        contact__c = cId,
	        c_acct_type_cd_fk__c = atcId,
	        c_prop_market_cd_fk__c = mktId
	    );

	    List<Id> contactIds = new List<Id>();
	    contactIds.add(cId);

	   GuestShelfDataCC.mockedWeeklyRequests.add(mockedWeeklyRequest);
	    List<GuestShelfDataCC.MarketingCampaignWeeklyWrapper> requestList = 
	    		GuestShelfDataCC.retrieveWeeklyByContacts(contactIds);
	    Test.stopTest();

	    system.debug('*** requestList ' + requestList);


	    System.assertEquals(1, requestList.size(), 'There should be 1 Marketing Campaign Weekly record'); 
	    System.assertEquals(cId, requestList[0].contact, 'The Marketing Campaign Weekly record should be for the contact'); 
	
	}

	@isTest static void testGetGuestShelfCampaignsLVMMock() {
		String cId = [SELECT Id FROM Contact LIMIT 1].id;
		String atcId = [SELECT Id FROM Account_Type_Code__c LIMIT 1].id;
		String mktId = [SELECT Id FROM Market__c LIMIT 1].id;
		Test.startTest();
	    marketing_lvm__x mockedLVMRequest = new marketing_lvm__x(
	        contact__c = cId,
	        c_acct_type_cd_fk__c = atcId,
	        c_prop_market_cd_fk__c = mktId
	    );

	    List<Id> contactIds = new List<Id>();
	    contactIds.add(cId);

	   GuestShelfDataCC.mockedLVMRequests.add(mockedLVMRequest);
	    List<GuestShelfDataCC.MarketingCampaignsLVMWrapper> requestList = 
	    		GuestShelfDataCC.retrieveLVMByContacts(contactIds);
	    Test.stopTest();

	    system.debug('*** requestList ' + requestList);


	    System.assertEquals(1, requestList.size(), 'There should be 1 Marketing LVM record'); 
	    System.assertEquals(cId, requestList[0].contact, 'The Marketing LVM record should be for the contact'); 
	
	}

	@isTest static void testGetGuestShelfCampaignsEnterpriseMock() {
		String cId = [SELECT Id FROM Contact LIMIT 1].id;

		Test.startTest();
	    enterprise_campaign__x mockedEntRequest = new enterprise_campaign__x(
	        contact__c = cId
	    );

	    List<Id> contactIds = new List<Id>();
	    contactIds.add(cId);

	   GuestShelfDataCC.mockedEnterpriseRequests.add(mockedEntRequest);
	    List<GuestShelfDataCC.EnterpriseCampaignWrapper> requestList = 
	    		GuestShelfDataCC.retrieveEnterpriseByContacts(contactIds);
	    Test.stopTest();

	    system.debug('*** requestList ' + requestList);


	    System.assertEquals(1, requestList.size(), 'There should be 1 Enterprise Campaign] record'); 
	    System.assertEquals(cId, requestList[0].contact, 'The Enterprise Campaign record should be for the contact'); 
	
	}

	@isTest static void testGetGuestShelfCampaignsDetMock() {
		String cId = [SELECT Id FROM Contact LIMIT 1].id;
		String atcId = [SELECT Id FROM Account_Type_Code__c LIMIT 1].id;
		String acctPropId = [SELECT Id FROM Account WHERE Name = 'DomPropAcctName' LIMIT 1].id;
		String mktId = [SELECT Id FROM Market__c LIMIT 1].id;
		Test.startTest();
	    marketing_campaigns__x mockedRequest = new marketing_campaigns__x(
	        contact__c = cId,
	        c_acct_type_cd_fk__c = atcId,
	        c_dom_cd_prop_fk__c = acctPropId,
	        c_dom_market_cd_fk__c = mktId,
	        ExternalId = '1'
	    );

	    List<String> externalIds = new List<String>();
	    externalIds.add('1');

	    GuestShelfDataCC.mockedRequests.add(mockedRequest);
	    List<GuestShelfDataCC.MarketingCampaignWrapper> requestList = 
	    		GuestShelfDataCC.retrieveMarketingCampaignDetails(externalIds);
	    Test.stopTest();

	    system.debug('*** requestList ' + requestList);

	    System.assertEquals(1, requestList.size(), 'There should be 1 Marketing Campaign record'); 
	    System.assertEquals(cId, requestList[0].contact, 'The Marketing Campaign record should be for the contact'); 
	
	}

	@isTest static void testGetGuestShelfCampaignsPropDetMock() {
		String cId = [SELECT Id FROM Contact LIMIT 1].id;
		String atcId = [SELECT Id FROM Account_Type_Code__c LIMIT 1].id;
		String acctPropId = [SELECT Id FROM Account WHERE Name = 'DomPropAcctName' LIMIT 1].id;
		String mktId = [SELECT Id FROM Market__c LIMIT 1].id;
		Test.startTest();
	    marketing_campaigns_properties__x mockedPropRequest = new marketing_campaigns_properties__x(
	        contact__c = cId,
	        c_acct_type_cd_fk__c = atcId,
	        c_dom_cd_prop_fk__c = acctPropId,
	        c_dom_market_cd_fk__c = mktId,
     		ExternalId = '1'
	    );

	    List<String> externalIds = new List<String>();
	    externalIds.add('1');

	   GuestShelfDataCC.mockedPropRequests.add(mockedPropRequest);
	    List<GuestShelfDataCC.MarketingCampaignPropertyWrapper> requestList = 
	    		GuestShelfDataCC.retrieveMarketingCampaignPropDetails(externalIds);
	    Test.stopTest();

	    system.debug('*** requestList ' + requestList);


	    System.assertEquals(1, requestList.size(), 'There should be 1 Marketing Campaign Property record'); 
	    System.assertEquals(cId, requestList[0].contact, 'The Marketing Campaign Property record should be for the contact'); 
	
	}

	@isTest static void testGetGuestShelfCampaignsWeeklyDetMock() {
		String cId = [SELECT Id FROM Contact LIMIT 1].id;
		String atcId = [SELECT Id FROM Account_Type_Code__c LIMIT 1].id;
		String mktId = [SELECT Id FROM Market__c LIMIT 1].id;
		Test.startTest();
	    marketing_campaigns_weekly__x mockedWeeklyRequest = new marketing_campaigns_weekly__x(
	        contact__c = cId,
	        c_acct_type_cd_fk__c = atcId,
	        c_prop_market_cd_fk__c = mktId,
	    	ExternalId = '1'
	    );

	    List<String> externalIds = new List<String>();
	    externalIds.add('1');

	   GuestShelfDataCC.mockedWeeklyRequests.add(mockedWeeklyRequest);
	    List<GuestShelfDataCC.MarketingCampaignWeeklyWrapper> requestList = 
	    		GuestShelfDataCC.retrieveWeeklyDetails(externalIds);
	    Test.stopTest();

	    system.debug('*** requestList ' + requestList);


	    System.assertEquals(1, requestList.size(), 'There should be 1 Marketing Campaign Weekly record'); 
	    System.assertEquals(cId, requestList[0].contact, 'The Marketing Campaign Weekly record should be for the contact'); 
	
	}

	@isTest static void testGetGuestShelfCampaignsLVMDetMock() {
		String cId = [SELECT Id FROM Contact LIMIT 1].id;
		String atcId = [SELECT Id FROM Account_Type_Code__c LIMIT 1].id;
		String mktId = [SELECT Id FROM Market__c LIMIT 1].id;
		Test.startTest();
	    marketing_lvm__x mockedLVMRequest = new marketing_lvm__x(
	        contact__c = cId,
	        c_acct_type_cd_fk__c = atcId,
	        c_prop_market_cd_fk__c = mktId,
	    	ExternalId = '1'
	    );

	    List<String> externalIds = new List<String>();
	    externalIds.add('1');

	   GuestShelfDataCC.mockedLVMRequests.add(mockedLVMRequest);
	    List<GuestShelfDataCC.MarketingCampaignsLVMWrapper> requestList = 
	    		GuestShelfDataCC.retrieveLVMDetails(externalIds);
	    Test.stopTest();

	    system.debug('*** requestList ' + requestList);


	    System.assertEquals(1, requestList.size(), 'There should be 1 Marketing LVM record'); 
	    System.assertEquals(cId, requestList[0].contact, 'The Marketing LVM record should be for the contact'); 
	
	}

	@isTest static void testGetGuestShelfCampaignsEnterpriseDetMock() {
		String cId = [SELECT Id FROM Contact LIMIT 1].id;

		Test.startTest();
	    enterprise_campaign__x mockedEntRequest = new enterprise_campaign__x(
	        contact__c = cId,
	    	ExternalId = '1'
	    );

	    List<String> externalIds = new List<String>();
	    externalIds.add('1');

	   GuestShelfDataCC.mockedEnterpriseRequests.add(mockedEntRequest);
	    List<GuestShelfDataCC.EnterpriseCampaignWrapper> requestList = 
	    		GuestShelfDataCC.retrieveEnterpriseDetails(externalIds);
	    Test.stopTest();

	    system.debug('*** requestList ' + requestList);


	    System.assertEquals(1, requestList.size(), 'There should be 1 Enterprise Campaign] record'); 
	    System.assertEquals(cId, requestList[0].contact, 'The Enterprise Campaign record should be for the contact'); 
	
	}
}