src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>POD__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Pod</description>
        <label>POD</label>
        <referenceTo>POD__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Property</fullName>
        <active>true</active>
        <description>Property</description>
        <label>Property</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Campaign_Project__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Market (Campaign and Marketing)</description>
        <inlineHelpText>Market (Campaign and Marketing)</inlineHelpText>
        <label>Market</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Market__c.Active_Flag__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Campaign Projects</relationshipLabel>
        <relationshipName>Campaign_Projects</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>POD__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>POD</description>
        <inlineHelpText>POD</inlineHelpText>
        <label>POD</label>
        <referenceTo>POD__c</referenceTo>
        <relationshipLabel>Campaign Projects</relationshipLabel>
        <relationshipName>Campaign_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Valid_End_Date__c</fullName>
        <description>Valid End Date</description>
        <inlineHelpText>Valid End Date</inlineHelpText>
        <label>Campaign Valid End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Valid_Start_Date__c</fullName>
        <description>Valid Start Date</description>
        <inlineHelpText>Valid Start Date</inlineHelpText>
        <label>Campaign Valid Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Campaign Project</label>
    <nameField>
        <displayFormat>CP{00000000}</displayFormat>
        <label>Campaign Project Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Campaign_Project_Property__c.object
<CustomObject>
    <description>The assignment of properties to a campaign project</description>
    <fields>
        <fullName>Campaign_Project__c</fullName>
        <description>Campaign Project</description>
        <inlineHelpText>Campaign Project</inlineHelpText>
        <label>Campaign Project</label>
        <referenceTo>Campaign_Project__c</referenceTo>
        <relationshipLabel>Campaign Project Properties</relationshipLabel>
        <relationshipName>Campaign_Project_Properties</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Campaign Project Property</label>
    <nameField>
        <displayFormat>CPP-{0000000000}</displayFormat>
        <label>Campaign Project Property Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Project Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Active_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Active Flag</description>
        <inlineHelpText>Active Flag</inlineHelpText>
        <label>Active Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_Code__c</fullName>
        <description>Market Code</description>
        <globalPicklist>Market</globalPicklist>
        <label>Market Code</label>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>POD__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>POD associated with this market</description>
        <inlineHelpText>POD associated with this market</inlineHelpText>
        <label>POD</label>
        <referenceTo>POD__c</referenceTo>
        <relationshipLabel>Market</relationshipLabel>
        <relationshipName>Market</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Market</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Offer_Definition__c.object
<CustomObject>
    <fields>
        <fullName>Campaign_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Campaign Project</description>
        <inlineHelpText>Campaign Project</inlineHelpText>
        <label>Campaign Project</label>
        <referenceTo>Campaign_Project__c</referenceTo>
        <relationshipLabel>Offer Definitions</relationshipLabel>
        <relationshipName>Offer_Definitions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Offer Description</description>
        <inlineHelpText>Offer Description</inlineHelpText>
        <label>Offer Description</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Max_Choice__c</fullName>
        <formula>CASE( text(Offer_Definition_Type__c) , &apos;Choice&apos;, 1,  Offer_Incentive_Group_Count__c +   NULLVALUE(Offer_Incentive_Count__c, 0) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Max Choice</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Offer_Definition_Type__c</fullName>
        <label>Offer Definition Type</label>
        <picklist>
            <picklistValues>
                <fullName>Choice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Package</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Offer_Employee_Description__c</fullName>
        <description>Information to help the Employee understand the terms and conditions for the Package.</description>
        <inlineHelpText>Information to help the Employee understand the terms and conditions for the Package.</inlineHelpText>
        <label>Offer Employee Description</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Offer_Guest_Label__c</fullName>
        <description>Offer Guest Label</description>
        <inlineHelpText>Offer Label is seen by the Guest. E.g. &quot;Join us for Summer Fun!&quot;</inlineHelpText>
        <label>Offer Guest Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Offer_Id__c</fullName>
        <description>Offer Id - system generated , 6 char base 30 alphanumeric number</description>
        <externalId>true</externalId>
        <inlineHelpText>System Generated Offer Number</inlineHelpText>
        <label>Offer Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Offer_Incentive_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Offer Incentive Group Count</description>
        <inlineHelpText>Offer Incentive Group Count</inlineHelpText>
        <label>Offer Incentive Count</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Offer_Intent__c</fullName>
        <description>Offer Intent</description>
        <inlineHelpText>Offer Intent</inlineHelpText>
        <label>Offer Intent</label>
        <picklist>
            <picklistValues>
                <fullName>BOUNCE BACK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HOTEL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NEW BUSINESS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPECIAL EVENTS</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Offer Definition</label>
    <nameField>
        <displayFormat>OD-{000000000}</displayFormat>
        <label>Offer Definition Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offer Definitions</pluralLabel>
    <recordTypes>
        <fullName>Package</fullName>
        <active>true</active>
        <description>Package offer has multiple offer incentives. For example Three free room night  AND $50 casino play AND $50 F&amp;B credit</description>
        <label>Package</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Offer_Incentive__c.object
<CustomObject>
    <description>Offer Incentive</description>
    <fields>
        <fullName>Market__c</fullName>
        <formula>IF(ISNULL( Offer_Definition__c ) ,IF(ISNULL( Offer_Incentive_Group__c ), &apos;&apos;,     Offer_Incentive_Group__r.Offer_Definition__r.Campaign_Project__r.Market_Text__c) , Offer_Definition__r.Campaign_Project__r.Market_Text__c  )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Market</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Offer_Definition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Offer Definition</description>
        <inlineHelpText>Lookup to Offer Definition</inlineHelpText>
        <label>Offer Definition</label>
        <referenceTo>Offer_Definition__c</referenceTo>
        <relationshipLabel>Offer Incentives</relationshipLabel>
        <relationshipName>Offer_Incentives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Offer_Incentive_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Offer Incentive Group</description>
        <inlineHelpText>Offer Incentive Group</inlineHelpText>
        <label>Offer Incentive Group</label>
        <referenceTo>Offer_Incentive_Group__c</referenceTo>
        <relationshipLabel>Offer Incentives</relationshipLabel>
        <relationshipName>Offer_Incentives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Valid_End_Date__c</fullName>
        <label>Valid End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Valid_Start_Date__c</fullName>
        <description>Valid start date for this incentive</description>
        <inlineHelpText>Valid start date for this incentive</inlineHelpText>
        <label>Valid Start Date</label>
        <type>Date</type>
    </fields>
    <label>Offer Incentive</label>
    <nameField>
        <displayFormat>OI-{0000000000}</displayFormat>
        <label>Offer Incentive Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offer Incentives</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Offer_Incentive_Group__c.object
<CustomObject>
    <description>Offer Incentive Group</description>
    <fields>
        <fullName>Max_Choice__c</fullName>
        <description>Out of the incentive choices, how many does the customer can choose from</description>
        <inlineHelpText>Out of the incentive choices, how many does the customer can choose from</inlineHelpText>
        <label>Max Choice</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Offer_Definition__c</fullName>
        <description>Which offer definition is this offer incentive group is associated with</description>
        <inlineHelpText>Which offer definition is this offer incentive group is associated with</inlineHelpText>
        <label>Offer Definition</label>
        <referenceTo>Offer_Definition__c</referenceTo>
        <relationshipLabel>Offer Incentive Group</relationshipLabel>
        <relationshipName>Offer_Incentive_Group</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Offer Incentive Group</label>
    <nameField>
        <displayFormat>OIG-{0000000000}</displayFormat>
        <label>Offer Incentive Group Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offer Incentive Group</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/POD__c.object
<CustomObject>
    <description>POD (Marketing)</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>POD Description</description>
        <inlineHelpText>POD Description</inlineHelpText>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>POD_Name__c</fullName>
        <description>POD Name</description>
        <globalPicklist>POD</globalPicklist>
        <inlineHelpText>POD Name</inlineHelpText>
        <label>POD Name</label>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>POD</label>
    <nameField>
        <displayFormat>P{00000}</displayFormat>
        <label>POD Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>POD</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OfferDefinitionLibraryControllerTest.cls
@IsTest
private class OfferDefinitionLibraryControllerTest{
     static testMethod void OfferDefinitionLibTest() {
     
         
         List <Account> accountList= TestFactory.properties;
         
         POD__c pocRec = new POD__c();
         pocRec.POD_Name__c = 'Atlantic City POD';
         insert pocRec;
         Market__c mar = new Market__c();
         mar.Name = 'testing';
         mar.Market_Code__c = 'ACM';
         mar.Active_Flag__c = true;
         mar.POD__c = pocRec.id; 
         insert mar;
         Campaign_Project__c campProject = new Campaign_Project__c();
         campProject.Market__c = mar.id;
         campProject.Valid_Start_Date__c = system.today();
         campProject.Valid_End_Date__c = system.today()+2;
         insert campProject;
         Offer_Definition__c OD = new Offer_Definition__c();
         OD.Campaign_Project__c = campProject.id;
         OD.Offer_Definition_Type__c = 'Package';
         OD.Offer_Employee_Description__c  ='test yu';
         OD.Description__c = 'test';
         OD.Offer_Guest_Label__c = 'test label1';
         OD.Offer_Id__c = '04578';
         OD.Offer_Intent__c = 'HOTEL';
         OD.Offer_Incentive_Count__c = 2;
         insert OD;
         Offer_Incentive_Group__c OIG = new Offer_Incentive_Group__c(Max_Choice__c = '2',Offer_Definition__c=OD.id,Offer_Incentive_Group_Label__c='Test Label2');
         insert OIG;
         Offer_Incentive__c OI = new Offer_Incentive__c();
         OI.Offer_Definition__c = OD.id;
         OI.Offer_Incentive_Group__c = OIG.id;
         OI.Offer_Incentive_Subcategory__c = 'CA';
         OI.Offer_Incentive_Category__c = 'GM';
         insert OI;
         
         
         Campaign_Project_Property__c CPP = new Campaign_Project_Property__c(Campaign_Project__c=campProject.id,Property__c=accountList[0].id);
         
        // Campaign_Project__c campProject = [select id from Campaign_Project__c where id='a140v0000004pPFAAY' limit 1];
         OfferDefinitionLibraryController offerDef = new OfferDefinitionLibraryController ();
         string strSearchParamter = '{"property":[""],"incentiveCategory":["GM"],"incentiveSubCategory":["CA"],"offerDescription":"test"}';
         List<OfferDefinitionLibraryDTO.OfferDefinition> offReslt = new List<OfferDefinitionLibraryDTO.OfferDefinition>();
         system.debug('resultValue');
         string resultValue = OfferDefinitionLibraryController.searchOffers(strSearchParamter);
         system.debug(resultValue +'--'+JSON.serialize(resultValue));
         offReslt = (List<OfferDefinitionLibraryDTO.OfferDefinition>) System.JSON.deserialize(resultValue, List<OfferDefinitionLibraryDTO.OfferDefinition>.class);
         system.debug('offReslt--->'+offReslt);
         string offerDefinitionId= offReslt[0].id;
         OfferDefinitionLibraryController.getOfferDetails(offerDefinitionId);
         
         string copyOfferDefinition= JSON.serialize(offReslt[0]);//'{"property":[""],"incentiveCategory":["LC"],"incentiveSubCategory":["BS"],"offerDescription":"test"}';
         OfferDefinitionLibraryController.copyOfferDefinition(campProject.id,copyOfferDefinition);
         
         string campaignProjectId= campProject.id;
         OfferDefinitionLibraryController.listSearchCriteria(campaignProjectId);
         
     }
}