src/objects/Campaign_Project__c.object
<CustomObject>
    <fields>
        <fullName>Direct_Mail_Drop_Date__c</fullName>
        <description>Drop Date for Direct Mail</description>
        <inlineHelpText>Drop Date for Direct Mail</inlineHelpText>
        <label>Campaign Direct Mail Drop Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email_Drop_Date__c</fullName>
        <description>Drop date for Campaign Email</description>
        <inlineHelpText>Drop date for Campaign Email</inlineHelpText>
        <label>Campaign Email Drop Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted for Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wrap Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Void</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMC Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>POD Approved</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Valid_End_Date__c</fullName>
        <description>Valid End Date</description>
        <inlineHelpText>Valid End Date</inlineHelpText>
        <label>Campaign Valid End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Valid_Start_Date__c</fullName>
        <description>Valid Start Date</description>
        <inlineHelpText>Valid Start Date</inlineHelpText>
        <label>Campaign Valid Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Campaign Project</label>
    <nameField>
        <displayFormat>CP{00000000}</displayFormat>
        <label>Campaign Project Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Campaign_Project_Workflow__c.object
<CustomObject>
    <fields>
        <fullName>Campaign_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign Project</label>
        <referenceTo>Campaign_Project__c</referenceTo>
        <relationshipLabel>Campaign Project Workflows</relationshipLabel>
        <relationshipName>Campaign_Project_Workflows</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Campaign Project Workflow</label>
    <nameField>
        <displayFormat>CPW-{0000}</displayFormat>
        <label>Campaign Project Workflow Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Project Workflows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Campaign_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign Project</label>
        <referenceTo>Campaign_Project__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Proforma__c.object
<CustomObject>
    <fields>
        <fullName>Campaign_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign Project</label>
        <referenceTo>Campaign_Project__c</referenceTo>
        <relationshipLabel>Proformas</relationshipLabel>
        <relationshipName>Proformas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted for Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Proforma</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Proforma Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proformas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CampaignProjectModelTest.cls
/*------------------------------------------------------------------------
Author:        Charu Goyal    
Company:       Salesforce
Description:   A test class created to validate the CampaignProjectModel and CampaignProjectTriggerHandler
               
History

10-July-17   Venkata Polavarapu - coomented out the controller logic as the TestFactory has been modifed
----------------------------------------------------------------------------*/

@isTest
private class CampaignProjectModelTest {
    @isTest static void test_Template_Association_Standard() {
        Test.startTest();
        
        list<Campaign_Project__c> lstCampProj= TestFactory.CampaignProjects ;
        Campaign_Project__c testCampProj = lstCampProj[0];
        
        List<Case> caseList = TestFactory.uniqueCasesInstance;
        caseList[0].Campaign_Project__c = lstCampProj[0].id;
        update caseList[0];
        
        testCampProj = lstCampProj[1];
        testCampProj.Email_Drop_Date__c = date.today()+1;
        testCampProj.Valid_End_Date__c = date.today()+5;
        testCampProj.Valid_Start_Date__c = date.today()+4;
        testCampProj.Direct_Mail_Drop_Date__c = date.today()+3;
        
        testCampProj.Status__c = 'Plan';
        DML.save(testCampProj); 
        
        testCampProj.Status__c = 'Submitted for Approval'; 
        DML.save(testCampProj);
        
        testCampProj.Status__c = 'Approved'; 
        DML.save(testCampProj);
        Campaign_Project_Workflow__c caProjectWork = TestFactory.addCampaignProjectWorkflow(lstCampProj[0]);
        testCampProj.Status__c = 'Rejected';
         
        DML.save(testCampProj);
        
        Test.stopTest();
    }
     @isTest static void ProformaModelTestMethod () {
        list<Campaign_Project__c> lstCampProj= TestFactory.CampaignProjects ;
        Campaign_Project__c testCampProj = lstCampProj[0];
        testCampProj.Status__c = 'Plan';
        DML.save(testCampProj);
        testCampProj.Status__c = 'Approved';
        DML.save(testCampProj);
        
        List<Case> caseList = TestFactory.uniqueCasesInstance;        
        caseList[0].Campaign_Project__c = testCampProj.id;
        caseList[0].subject = 'test Approve Pro Formation';
        DML.save(caseList[0]);
        
        testCampProj.Email_Drop_Date__c = date.today()+1;
        testCampProj.Valid_End_Date__c = date.today()+5;
        testCampProj.Valid_Start_Date__c = date.today()+4;
        testCampProj.Direct_Mail_Drop_Date__c = date.today()+3;
        
        testCampProj.Status__c = 'Plan';
        DML.save(testCampProj); 
        
        testCampProj.Status__c = 'Submitted for Approval'; 
        DML.save(testCampProj);
                
        List<Proforma__c> proList = TestFactory.getCampaignProjectProformaLst;      
        proList[0].Campaign_Project__c = lstCampProj[1].id;
        DML.save(proList);
        
        proList[0].Campaign_Project__c = testCampProj.id;
        proList[0].Status__c = 'Approved';
        DML.save(proList);
    }
}