src/objects/Campaign_Project__c.object
<CustomObject>
    <fields>
        <fullName>Campaign_Redemption_Channel__c</fullName>
        <label>Campaign Redemption Channel</label>
        <picklist>
            <picklistValues>
                <fullName>PlaybyTR-Mobile messaging</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hotel System</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Table Voucher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Digital RSVP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Total Rewards.com</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Media</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Play by TR - Mobile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Telemarketing (Host)-Outbound</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call Center - Inbound</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 line reader (slot Machine)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRISM display (slot Machine)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kiosks APS Promo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kiosks TR Enhanced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TotalRewards.com</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Facebook</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Twitter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Instagram</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Snapchat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Groupon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yelp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open Table</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Redemption_Channel__c</fullName>
        <globalPicklist>Redemption_Channel</globalPicklist>
        <label>Redemption Channel</label>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Campaign Project</label>
    <nameField>
        <displayFormat>CP{00000000}</displayFormat>
        <label>Campaign Project Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Offer_Incentive__c.object
<CustomObject>
    <description>Offer Incentive</description>
    <fields>
        <fullName>Project_Campaign_Offer_Redemption_Key__c</fullName>
        <description>This field will be used by developer to find the campaign project ID and if it has redemption values</description>
        <formula>if(isblank(Offer_Definition__r.Campaign_Project__r.Id),&apos;NoProject&apos;,Offer_Definition__r.Campaign_Project__r.Id) 

+&apos;$&lt;id&gt;$&apos;+  
if(isblank(Offer_Definition__r.Campaign_Project__r.Redemption_Channel__c),&apos;NoValues&apos;,&apos;HasValues&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Campaign Offer Redemption Key</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Redemption_Channel__c</fullName>
        <globalPicklist>Campaign_Redemption_Channel</globalPicklist>
        <label>Redemption Channel</label>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Offer Incentive</label>
    <nameField>
        <displayFormat>OI-{0000000000}</displayFormat>
        <label>Offer Incentive Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offer Incentives</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/OfferIncentiveHelper.cls
public class OfferIncentiveHelper
{
    public static void OfferIncentiveUpdates(list<Offer_Incentive__c> OfferIncentiveLst)
    {
        set<string> projectIds = new set<string> ();
        for(Offer_Incentive__c oi:OfferIncentiveLst)
        {
            
            if(oi.Project_Campaign_Offer_Redemption_Key__c!=null && 
                oi.Project_Campaign_Offer_Redemption_Key__c.substringAfter('$<id>$')=='HasValues'
                && oi.Project_Campaign_Offer_Redemption_Key__c.substringBefore('$<id>$')!='NoProject')
            {
                system.debug('adding to pid set'+oi.Project_Campaign_Offer_Redemption_Key__c.substringBefore('$<id>$'));
                projectIds.add(oi.Project_Campaign_Offer_Redemption_Key__c.substringBefore('$<id>$'));
            }
           // 
        }
        map<string,string> mapprojectRedemptionChannel = new map<string,string> ();
        system.debug('pid are'+projectIds);
        if(projectIds.size()>0)
        {
            for( Campaign_Project__c cp:[select id, Redemption_Channel__c,Campaign_Redemption_Channel__c   from Campaign_Project__c where id=:projectIds])
            {
                 system.debug(cp.id+' <<id >> Redemption >>'+cp.Redemption_Channel__c);
                mapprojectRedemptionChannel.put( String.valueOf(cp.id).substring(0, 15),cp.Campaign_Redemption_Channel__c);
                
            }
        }
        
        for(Offer_Incentive__c oi:OfferIncentiveLst)
        {
            if(oi.Redemption_Channel__c !=null)
            {
                if( oi.Project_Campaign_Offer_Redemption_Key__c.substringBefore('$<id>$')!='NoProject'&& mapprojectRedemptionChannel!=null
                    && mapprojectRedemptionChannel.get(oi.Project_Campaign_Offer_Redemption_Key__c.substringBefore('$<id>$'))!=null )
                {
                    if(oi.Redemption_Channel__c.contains(';'))
                    {
                        if(isValidSelection(oi.Redemption_Channel__c.split(';'),mapprojectRedemptionChannel.get(oi.Project_Campaign_Offer_Redemption_Key__c.substringBefore('$<id>$'))))
                        {
                            continue;
                        }else{
                            oi.adderror('match with Projects Redemption Values ');
                        }
                    }else{
                        list<string> lsts= new list<string>();
                        lsts.add(oi.Redemption_Channel__c);
                        if(isValidSelection(lsts,mapprojectRedemptionChannel.get(oi.Project_Campaign_Offer_Redemption_Key__c.substringBefore('$<id>$'))))
                        //if(mapprojectRedemptionChannel.get(oi.Project_Campaign_Offer_Redemption_Key__c.substringBefore('$<id>$')).contains(oi.Redemption_Channel__c))
                       // if(oi.Redemption_Channel__c.contains(mapprojectRedemptionChannel.get(oi.Project_Campaign_Offer_Redemption_Key__c.substringBefore('$<id>$'))))
                        {
                            continue;
                        }else{
                            system.debug(mapprojectRedemptionChannel.get(oi.Project_Campaign_Offer_Redemption_Key__c.substringBefore('$<id>$')));
                            oi.adderror('Should match with Projects Redemption Values ');
                        }
                    }
                    //if(isValidSelection())
                }else{
                    system.debug('no proj'+oi.Project_Campaign_Offer_Redemption_Key__c.substringBefore('$<id>$'));
                    oi.adderror('It Looks like their is no Campaign project Associated, so you may not add a value to Redemption Channel');
                }
                
                
            }else{
                system.debug('check>');
                if( oi.Project_Campaign_Offer_Redemption_Key__c!=null && 
                oi.Project_Campaign_Offer_Redemption_Key__c.substringAfter('$<id>$')=='HasValues'
                && oi.Project_Campaign_Offer_Redemption_Key__c.substringBefore('$<id>$')!='NoProject')
                {
                    system.debug('a >');
                    if(mapprojectRedemptionChannel!=null && mapprojectRedemptionChannel.get(oi.Project_Campaign_Offer_Redemption_Key__c.substringBefore('$<id>$'))!=null)
                    system.debug('aa>');
                    oi.Redemption_Channel__c = mapprojectRedemptionChannel.get(oi.Project_Campaign_Offer_Redemption_Key__c.substringBefore('$<id>$')) ;
                }
            }
            
            
        }
        
    
    }
    
     public static Boolean isValidSelection(list<string> SelectedPicklists, String projectRedeptionValue){

        for(String eachInterest : SelectedPicklists){
            //if(a=a){}
            system.debug('eachInterest'+eachInterest );
            if(!projectRedeptionValue.containsIgnoreCase(eachInterest)){
                return false;

            }

        }

        return true;

    }
    
    

}