src/objects/Campaign_Project__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Market (Campaign and Marketing)</description>
        <inlineHelpText>Market (Campaign and Marketing)</inlineHelpText>
        <label>Market</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Market__c.Active_Flag__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Campaign Projects</relationshipLabel>
        <relationshipName>Campaign_Projects</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Valid_End_Date__c</fullName>
        <description>Valid End Date</description>
        <inlineHelpText>Valid End Date</inlineHelpText>
        <label>Campaign Valid End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Valid_Start_Date__c</fullName>
        <description>Valid Start Date</description>
        <inlineHelpText>Valid Start Date</inlineHelpText>
        <label>Campaign Valid Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Campaign Project</label>
    <nameField>
        <displayFormat>CP{00000000}</displayFormat>
        <label>Campaign Project Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Market</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Offer_Definition__c.object
<CustomObject>
    <fields>
        <fullName>Campaign_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Campaign Project</description>
        <inlineHelpText>Campaign Project</inlineHelpText>
        <label>Campaign Project</label>
        <referenceTo>Campaign_Project__c</referenceTo>
        <relationshipLabel>Offer Definitions</relationshipLabel>
        <relationshipName>Offer_Definitions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Offer Description</description>
        <inlineHelpText>Offer Description</inlineHelpText>
        <label>Offer Description</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Max_Choice__c</fullName>
        <formula>CASE( text(Offer_Definition_Type__c) , &apos;Choice&apos;, 1,  Offer_Incentive_Group_Count__c +   NULLVALUE(Offer_Incentive_Count__c, 0) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Max Choice</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Offer_Definition_Type__c</fullName>
        <label>Offer Definition Type</label>
        <picklist>
            <picklistValues>
                <fullName>Choice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Package</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Offer_Employee_Description__c</fullName>
        <description>Information to help the Employee understand the terms and conditions for the Package.</description>
        <inlineHelpText>Information to help the Employee understand the terms and conditions for the Package.</inlineHelpText>
        <label>Offer Employee Description</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Offer_Guest_Label__c</fullName>
        <description>Offer Guest Label</description>
        <inlineHelpText>Offer Label is seen by the Guest. E.g. &quot;Join us for Summer Fun!&quot;</inlineHelpText>
        <label>Offer Guest Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Offer_Id__c</fullName>
        <description>Offer Id - system generated , 6 char base 30 alphanumeric number</description>
        <externalId>true</externalId>
        <inlineHelpText>System Generated Offer Number</inlineHelpText>
        <label>Offer Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Offer Definition</label>
    <nameField>
        <displayFormat>OD-{000000000}</displayFormat>
        <label>Offer Definition Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offer Definitions</pluralLabel>
    <recordTypes>
        <fullName>Choice</fullName>
        <active>true</active>
        <description>Choice Offer is also known as &apos;OR&apos; Offer. For example, Three free room night  OR  $50 casino play</description>
        <label>Choice</label>
    </recordTypes>
    <recordTypes>
        <fullName>Package</fullName>
        <active>true</active>
        <description>Package offer has multiple offer incentives. For example Three free room night  AND $50 casino play AND $50 F&amp;B credit</description>
        <label>Package</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Offer_Incentive__c.object
<CustomObject>
    <description>Offer Incentive</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>The Amount is a dollar value or a %. 
E.g. You can have 5 dollars off
E.g. You can have 5% off.</description>
        <inlineHelpText>The Amount is a dollar value or a %. 
E.g. You can have 5 dollars off
E.g. You can have 5% off.</inlineHelpText>
        <label>Amount</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Employee_Description__c</fullName>
        <description>Offer Description for Employee</description>
        <inlineHelpText>Offer Description for Employee</inlineHelpText>
        <label>Employee Description</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Guest_Description__c</fullName>
        <description>The Guest Description is a long description displayed on Guest View Channels. Business wants 3K characters.</description>
        <inlineHelpText>The Guest Description is a long description displayed on Guest View Channels. Business wants 3K characters.</inlineHelpText>
        <label>Guest Description</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <formula>IF(ISNULL( Offer_Definition__c ) ,IF(ISNULL( Offer_Incentive_Group__c ), &apos;&apos;,     Offer_Incentive_Group__r.Offer_Definition__r.Campaign_Project__r.Market_Text__c) , Offer_Definition__r.Campaign_Project__r.Market_Text__c  )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Market</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Offer_Definition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Offer Definition</description>
        <inlineHelpText>Lookup to Offer Definition</inlineHelpText>
        <label>Offer Definition</label>
        <referenceTo>Offer_Definition__c</referenceTo>
        <relationshipLabel>Offer Incentives</relationshipLabel>
        <relationshipName>Offer_Incentives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Offer_Incentive_Category__c</fullName>
        <description>Offer Incentive Category</description>
        <globalPicklist>Offer_Incentive_Category</globalPicklist>
        <inlineHelpText>Offer Incentive Category</inlineHelpText>
        <label>Incentive Category</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Offer_Incentive_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Offer Incentive Group</description>
        <inlineHelpText>Offer Incentive Group</inlineHelpText>
        <label>Offer Incentive Group</label>
        <referenceTo>Offer_Incentive_Group__c</referenceTo>
        <relationshipLabel>Offer Incentives</relationshipLabel>
        <relationshipName>Offer_Incentives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Offer_Incentive_Id__c</fullName>
        <description>Offer Incentive Id</description>
        <inlineHelpText>Offer Incentive Id</inlineHelpText>
        <label>Offer Incentive Id</label>
        <length>13</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Offer_Incentive_Subcategory__c</fullName>
        <description>Offer Incentive Subcategory</description>
        <globalPicklist>Offer_Incentive_Subcategory</globalPicklist>
        <inlineHelpText>Offer Incentive Subcategory</inlineHelpText>
        <label>Incentive Subcategory</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Valid_End_Date__c</fullName>
        <label>Valid End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Valid_Start_Date__c</fullName>
        <description>Valid start date for this incentive</description>
        <inlineHelpText>Valid start date for this incentive</inlineHelpText>
        <label>Valid Start Date</label>
        <type>Date</type>
    </fields>
    <label>Offer Incentive</label>
    <nameField>
        <displayFormat>OI-{0000000000}</displayFormat>
        <label>Offer Incentive Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offer Incentives</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Offer_Incentive_Group__c.object
<CustomObject>
    <description>Offer Incentive Group</description>
    <fields>
        <fullName>Max_Choice__c</fullName>
        <description>Out of the incentive choices, how many does the customer can choose from</description>
        <inlineHelpText>Out of the incentive choices, how many does the customer can choose from</inlineHelpText>
        <label>Max Choice</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Offer_Definition__c</fullName>
        <description>Which offer definition is this offer incentive group is associated with</description>
        <inlineHelpText>Which offer definition is this offer incentive group is associated with</inlineHelpText>
        <label>Offer Definition</label>
        <referenceTo>Offer_Definition__c</referenceTo>
        <relationshipLabel>Offer Incentive Group</relationshipLabel>
        <relationshipName>Offer_Incentive_Group</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Offer_Incentive_Group_Label__c</fullName>
        <description>A short label used internally for report and identification of the offer incentive group</description>
        <inlineHelpText>A short label used internally for report and identification of the offer incentive group</inlineHelpText>
        <label>Offer Incentive Group Label</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Offer Incentive Group</label>
    <nameField>
        <displayFormat>OIG-{0000000000}</displayFormat>
        <label>Offer Incentive Group Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offer Incentive Group</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/OfferDefinitionLibraryDTO.cls
/**
 *  @author Ivan Yeung
 *  @date 07/12/2017
 *  @group DTO
 *  @description  data transfer object to supprt the offer definiton library features
 */


public with sharing class OfferDefinitionLibraryDTO {

    public static final String PROPERTY_CODE_ALL = 'All'; // special value to represent all properties in search critiera
    public static final String CATEGORY_CODE_ALL = 'All';
    public static final String SUBCATEGORY_CODE_ALL = 'All';


    /**
    * @description - the dto of offer defintion, it can be used as of list of offer for search result. It can also be used as offer detail display
    */
    public class OfferDefinition implements Comparable {

        public string campaignProjectId; // the campaign project where this offer definition is associated with
        public String name;
        public String id; // offer definition record id
        public String offerId; // base60 string for display
        public Integer maxChoice;
        public String offerDefinitionType; // Choice or Package offer definition
        public String description;
        public String guestLabel;
        public String employeeDescription;
        public Integer offerIncentiveCount;
        public Integer offerIncentiveGroupCount;
        public boolean ottr;

        public List<OfferIncentiveGroup> offerIncentiveGroups;
        public List<OfferIncentive> offerIncentives;

        public Integer weight; // for sorting
        public decimal relevance; // relevance score for the search result. the vaule is from 0 to 1. the highest the number the more relevant. For this display, we should show as percentage.

        /**
        *  @description compare method so that the higher weight come first
         */
        public Integer compareTo(Object compareTo) {

            OfferDefinition offer = (OfferDefinition)compareTo;
            Integer weightA = this.weight == null ? 0 : this.weight;
            Integer weightB = offer.weight == null ? 0 : offer.weight;

            return weightB - weightA;

        }

        // default constructor
        public OfferDefinition(){}

        public OfferDefinition(Offer_Definition__c od){
            campaignProjectId = od.Campaign_Project__c;
            name = od.name;
            id = od.Id;
            offerId = od.Offer_Id__c;
            maxChoice = od.Max_Choice__c.intValue();
            offerDefinitionType = od.Offer_Definition_Type__c;
            description = String.isBlank(od.Description__c)?od.Offer_Id__c: od.Description__c ;
            // to do: confirm label and desc mapping
            guestLabel = String.isBlank(od.Offer_Guest_Label__c)?od.Offer_Id__c: od.Offer_Guest_Label__c ;
            employeeDescription = String.isBlank(od.Offer_Employee_Description__c)?od.Offer_Id__c: od.Offer_Employee_Description__c ;

        }

        // only map those fields used for udpate / insert
        public Offer_Definition__c ToObject(){

            Offer_Definition__c offer = new Offer_Definition__c();
            offer.id = id;
            offer.Campaign_Project__c = campaignProjectId;
            offer.Offer_Definition_Type__c = offerDefinitionType;
            offer.Description__c = description;
            offer.Offer_Guest_Label__c = guestLabel;
            offer.Offer_Employee_Description__c = employeeDescription;

            return offer;

        }


        }


    /**
    * @description DTO class for Offer_Incentive_Group__c object
    */
    public class OfferIncentiveGroup {

        public String id; // offer incentive group recordId;
        public String name;
        public String offerDefinitionId;
        // public String offerIncentiveGroupId; // base 30 id for display
        public String offerIncentiveGroupLabel;
        public Integer maxChoice;

        public List <OfferIncentive> offerIncentives;

        public OfferIncentiveGroup(){}

        public OfferIncentiveGroup(Offer_Incentive_Group__c o ){
            id = o.Id;
            name = o.name;
            offerDefinitionId = o.Offer_Definition__c;
            offerIncentiveGroupLabel = String.isBlank(o.Offer_Incentive_Group_Label__c)? o.name: o.Offer_Incentive_Group_Label__c;
            maxChoice = o.Max_Choice__c == null? 1: Integer.valueOf(o.Max_Choice__c);
        }

        // only map those fields used for udpate / insert
        public Offer_Incentive_Group__c ToObject(){
            Offer_Incentive_Group__c o = new Offer_Incentive_Group__c(Offer_Definition__c = offerDefinitionId);
            o.Id = id;
            o.Offer_Incentive_Group_Label__c = offerIncentiveGroupLabel;
            o.Max_Choice__c = String.valueOf(  maxChoice) ; // max Choice is a picklist

            return o;
        }

    }



    /**
    * @description DTO class for Offer_Incentive__c object
    */
    public class OfferIncentive {

        public String id; // offer incentive recordId;
        public String name;
        public String offerIncentiveGroupId;
        public String offerDefinitionId;
        public String offerIncentiveId; // base 30 id for display
        public Decimal amount;
        String offerIncentiveCategory;
        String offerIncentiveSubcategory;
        public String guestDescription;
        public String guestLabel;
        public String employeeDescription;
        public String market;
        public Date validStartDate;
        public Date validEndDate;
        public Integer maxRedemption;

        public OfferIncentive(){}

        public OfferIncentive(Offer_Incentive__c o){
            id = o.id;
            name = o.name;
            offerIncentiveGroupId = o.Offer_Incentive_Group__c;
            offerDefinitionId = o.Offer_Definition__c;
            offerIncentiveId = o.Offer_Incentive_Id__c;  // base 30 id
            amount = o.Amount__c;
            offerIncentiveCategory = o.Offer_Incentive_Category__c;
            offerIncentiveSubcategory = o.Offer_Incentive_Subcategory__c;
            guestDescription = String.isBlank(o.Guest_Description__c)? o.Offer_Incentive_Id__c: o.Guest_Description__c ;
            guestLabel = String.isBlank(o.Guest_Description__c)? o.Offer_Incentive_Id__c: o.Guest_Description__c ; // TO DO: MAP TO NEW FIELD
            employeeDescription = String.isBlank(o.Employee_Description__c)? o.Offer_Incentive_Id__c: o.Employee_Description__c ;
            market = o.Market__c;
            validEndDate = o.Valid_End_Date__c;
            validStartDate = o.Valid_Start_Date__c;
            maxRedemption = Integer.valueOf(o.Max_Redemption__c);
        }

        public Offer_Incentive__c ToObject(){

            Offer_Incentive__c o = new Offer_Incentive__c();
            o.id = id;
            o.Offer_Incentive_Group__c = offerIncentiveGroupId;
            o.Offer_Definition__c = offerDefinitionId;
            o.Amount__c = amount;
            o.Offer_Incentive_Category__c = offerIncentiveCategory;
            o.Offer_Incentive_Subcategory__c = offerIncentiveSubcategory;
            o.Guest_Description__c = guestDescription;
            // o.Guest_Label__c guestLabel;  TBD
            o.Employee_Description__c = employeeDescription;
            o.Valid_Start_Date__c = validStartDate;
            o.Valid_End_Date__c = validEndDate;
            o.Max_Redemption__c = String.valueOf(maxRedemption);

            return o;
        }

    }

    /**
    * @description provide the data structure for the search paramters. It is meant to provide to input for the search functions
    */
    public class SearchParamters {

        // NOTE: if the user choose 'All' , return all the items in the list. in the futuer, we might allow mulit-pick

        public List <String> property; // assume it is single property for now
        public List <String> incentiveCategory; // this is the incentive category code, not the descripiton value
        public List <String> incentiveSubCategory;
        public String offerDescription; // search the offer label, offer incentive or offer incentive group
        

    }


    /**
    * @description provide the data structure for the search critiera. It is meant to provide search critiera to be displayed in Offer Definition Library
    */
    public class SearchCriteria {

        // String market;
        // Date validStartDate;
        // Date validEndDate;
        public Map <String, String> properties; // key=propery code, value = property descriptino for display
        public Map <String, String> incentiveCategories; // key=category code, value = incentive category desc
        public Map <String, String> incentiveSubCategories; // key=subcategory code, value = incentive Sub category desc
        public String offerDescription; // offer description or offer label search string
        

    }


    public static final Integer STATUS_SERVER_ERROR_CODE = 500;
    public static final Integer STATUS_OK = 200;
    /**
    * @description  service status
    *     status code will use http status convention
    *         1xx Informational responses
    *         2xx Success
    *         5xx Server errors
     */
    public class Status {
        public Integer statusCode;
        public String statusDescription;
    }

}