src/objects/Campaign_Project__c.object
<CustomObject>
    <label>Campaign Project</label>
    <nameField>
        <displayFormat>CP{00000000}</displayFormat>
        <label>Campaign Project Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Offer_Definition__c.object
<CustomObject>
    <fields>
        <fullName>Campaign_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Campaign Project</description>
        <inlineHelpText>Campaign Project</inlineHelpText>
        <label>Campaign Project</label>
        <referenceTo>Campaign_Project__c</referenceTo>
        <relationshipLabel>Offer Definitions</relationshipLabel>
        <relationshipName>Offer_Definitions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Offer Definition</label>
    <nameField>
        <displayFormat>OD-{000000000}</displayFormat>
        <label>Offer Definition Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offer Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OfferDefinitionModelTest.cls
/*------------------------------------------------------------------------
Author:        Venkata Polavarapu    
Company:       Salesforce
Description:   A test class created to validate the OfferDefinitionModel and OfferDefinitionTriggerHandler
               
History

10-July-17   Venkata Polavarapu Utilize the TestFactory utility to get the Campaign_Project__c,Offer_Definition__c data
----------------------------------------------------------------------------*/


@isTest
private class OfferDefinitionModelTest {
    @isTest static void test_Template_Association_Standard() {
      
        list<Campaign_Project__c> lstCampProj= TestFactory.CampaignProjects   ;  
        system.debug('Campaign_Project__c'+lstCampProj);
        
        List <Offer_Definition__c> lstOfferDefinitions =TestFactory.addOfferDefinitions(lstCampProj[0]);
        system.debug('Offer_Definition__c'+lstOfferDefinitions);
        
        
        Offer_Definition__c testoffer = lstOfferDefinitions[0];
        Test.startTest();
        DML.save(testoffer);
        Test.stopTest();       
    } 

}