src/objects/Campaign_Project__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted for Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wrap Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Void</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMC Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>POD Approved</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Campaign Project</label>
    <nameField>
        <displayFormat>CP{00000000}</displayFormat>
        <label>Campaign Project Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Campaign_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign Project</label>
        <referenceTo>Campaign_Project__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dependencies__c</fullName>
        <label>Dependencies</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CaseModelTest.cls
@isTest
private class CaseModelTest {
	
	@isTest static void testCaseWithOneDependency() {
		list<Campaign_Project__c> lstCampProj= TestFactory.CampaignProjects ;
		Campaign_Project__c testCampProj = lstCampProj[0];
		testCampProj.Status__c = 'Plan';
		DML.save(testCampProj);
		testCampProj.Status__c = 'Approved';
		DML.save(testCampProj);

		List<Case> relatedCases = [select Id,Status,Order__c,Dependencies__c, Campaign_Project__c from Case where Campaign_Project__c =: testCampProj.Id and RecordType.Name = 'Campaign Workflow Instance'];
		Test.startTest();
		relatedCases[0].Status = 'Completed';
		DML.save(relatedCases[0]);
		Test.stopTest();
		relatedCases = [select Id,Status,Order__c,Dependencies__c, Campaign_Project__c from Case where Campaign_Project__c =: testCampProj.Id and RecordType.Name = 'Campaign Workflow Instance'];
		system.assertEquals(relatedCases[1].Status,'Ready to Start');
		system.assertEquals(relatedCases[2].Status,'Not Started');
	}
	
	@isTest static void test_method_two() {
		list<Campaign_Project__c> lstCampProj= TestFactory.CampaignProjects ;
		Campaign_Project__c testCampProj = lstCampProj[0];
		testCampProj.Status__c = 'Plan';
		DML.save(testCampProj);
		testCampProj.Status__c = 'Approved';
		DML.save(testCampProj);

		List<Case> relatedCases = [select Id,Status,Order__c,Dependencies__c, Campaign_Project__c from Case where Campaign_Project__c =: testCampProj.Id and RecordType.Name = 'Campaign Workflow Instance'];
		relatedCases[0].Status = 'Completed';
		relatedCases[1].Status = 'Completed';
		Test.startTest();
		DML.save(relatedCases[0]);
		DML.save(relatedCases[1]);
		Test.stopTest();
		relatedCases = [select Id,Status,Order__c,Dependencies__c, Campaign_Project__c from Case where Campaign_Project__c =: testCampProj.Id and RecordType.Name = 'Campaign Workflow Instance'];
		system.assertEquals(relatedCases[2].Status,'Ready to Start');
	}
	
}