src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>MS_DM_Drop_Date__c</fullName>
        <description>Target Due date for the milestone DM Drop Date</description>
        <inlineHelpText>Target Due date for the milestone DM Drop Date</inlineHelpText>
        <label>MS DM Drop Due Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MS_Email_Drop_Date__c</fullName>
        <description>Target Due date for the milestone Email Drop Date</description>
        <inlineHelpText>Target Due date for the milestone Email Drop Date</inlineHelpText>
        <label>MS Email Drop Due Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MS_Email_Job_Complete__c</fullName>
        <description>Target Due date for the milestone Email Job Complete</description>
        <inlineHelpText>Target Due date for the milestone Email Job Complete</inlineHelpText>
        <label>MS Email Job Complete Due</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MS_Email_Job_Start__c</fullName>
        <description>Target Due date for the milestone Email Job Start</description>
        <inlineHelpText>Target Due date for the milestone Email Job Start</inlineHelpText>
        <label>MS Email Job Start Due</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MS_Email_Proof_Approved__c</fullName>
        <description>Target Due date for the milestone Email Proof Approved</description>
        <inlineHelpText>Target Due date for the milestone Email Proof Approved</inlineHelpText>
        <label>MS Email Proof Approved Due</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MS_POD_Submitted_Job__c</fullName>
        <description>Target Due date for the milestone POD Submitted Job</description>
        <inlineHelpText>Target Due date for the milestone POD Submitted Job</inlineHelpText>
        <label>MS POD Submitted Job Due</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MS_Proforma_Approved__c</fullName>
        <description>Timestamp for the due date of the milestone Proforma Approved</description>
        <inlineHelpText>Timestamp for the due date of the milestone Proforma Approved</inlineHelpText>
        <label>MS Proforma Approved Due</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MS_R_R_Approved__c</fullName>
        <description>Timestamp for the due date of the milestone R&amp;R Approved</description>
        <inlineHelpText>Timestamp for the due date of the milestone R&amp;R Approved</inlineHelpText>
        <label>MS R&amp;R Approved Due</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MS_Standard_Campaign_Project_Complete__c</fullName>
        <description>Timestamp for the due date of milestone Standard Campaign Project Complete</description>
        <inlineHelpText>Timestamp for the due date of milestone Standard Campaign Project Complete</inlineHelpText>
        <label>MS Campaign Project Complete Due</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MS_Standard_Project_Kickoff__c</fullName>
        <description>Target Due date for the milestone Standard Project Kickoff</description>
        <inlineHelpText>Target Due date for the milestone Standard Project Kickoff</inlineHelpText>
        <label>MS Standard Project Kickoff Due</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MS_Studio_Art_Approved__c</fullName>
        <description>Timestamp of the due date for milestone Studio Art Approved</description>
        <inlineHelpText>Timestamp of the due date for milestone Studio Art Approved</inlineHelpText>
        <label>MS Studio Art Approved Due</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MS_Studio_Job_Complete__c</fullName>
        <description>Timestamp of the due date for milestone Studio Job Complete</description>
        <inlineHelpText>Timestamp of the due date for milestone Studio Job Complete</inlineHelpText>
        <label>MS Studio Job Complete Due</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CaseCampaignMilestoneTimeCalculator.cls
/**
 *  @author Ivan Yeung
 *  @date 7/22/17
 *  @group Entitlement
 *  @description  The implementation of Support.MilestoneTriggerTimeCalculator interface to support the calcuation of the milestone trigger time
 */


global with sharing class CaseCampaignMilestoneTimeCalculator implements Support.MilestoneTriggerTimeCalculator  {


    /*******************************************************************************************************
    * @description implmentation of interface's calculateMilestoneTriggerTime
    * @param String caseId, String milestoneTypeId
    * @return the milestone time in term of minutes
    *
    */
    global Integer calculateMilestoneTriggerTime(String caseId, String milestoneTypeId) {

        // depend upon the miletone type , get the time stamp from the case.

        Case c = [SELECT MS_DM_Drop_Date__c, MS_Email_Drop_Date__c, MS_Email_Job_Complete__c, MS_Email_Job_Start__c, MS_Email_Proof_Approved__c, MS_POD_Submitted_Job__c, MS_Proforma_Approved__c, MS_R_R_Approved__c, MS_Standard_Campaign_Project_Complete__c, MS_Standard_Project_Kickoff__c, MS_Studio_Art_Approved__c, MS_Studio_Job_Complete__c FROM Case WHERE Id=:caseId limit 1];
        MilestoneType mt = [SELECT Name FROM MilestoneType WHERE Id=:milestoneTypeId limit 1];

        String milestoneTimeStampField = CaseModel.milestoneTimeStampMap.get(mt.Name.toUpperCase());  // assumption: the milestone type name is the same as the drop down of the campaign milestone in the case
        Integer milestoneTime = 0;

        if (String.isNotBlank(milestoneTimeStampField)){
            Datetime dueDateTime = (Datetime) c.get(milestoneTimeStampField);
            milestoneTime = (BusinessHours.diff(BusinessHourUtil.caesarsBusinessWeek.Id ,  Datetime.now(), dueDateTime) / (60 *1000)) .intValue();
        }


        return  milestoneTime;



    }

}