src/objects/Customer_Info_External_c__x.object
<CustomObject>
    <description>Customer_Info_External__c</description>
    <externalDataSource>CustomApexHerokuConnector</externalDataSource>
    <externalName>caesars$customer_info</externalName>
    <fields>
        <fullName>RecordType__c</fullName>
        <description>RecordType</description>
        <externalDeveloperName>RecordType</externalDeveloperName>
        <label>RecordType</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <externalDeveloperName>contact</externalDeveloperName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Customer_Info_External_c</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Info</label>
    <pluralLabel>Customer Infos</pluralLabel>
</CustomObject>

src/classes/CustomerInfoDetailControllerCC.cls
public with sharing class CustomerInfoDetailControllerCC {

   // @AuraEnabled
   // public static List<Customer_Info_External_c__x> loadDetail() {
        //return [SELECT ExternalId FROM Customer_Info_External_c__x LIMIT 50];
    //    return [SELECT Id, contact__c, ExternalId, RecordType__c FROM Customer_Info_External_c__x WHERE contact__r.Id = '0030v000002bWbz'];
    //}
    
    //@AuraEnabled
   // public static Customer_Info_External_c__x findById(String customerInfoId) {
   //     return [SELECT RecordType__c, ExternalId
    //            FROM Customer_Info_External_c__x 
   //             WHERE Id = :customerInfoId];
    //}
}